name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Atualizando para v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Usando a versão mais recente

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Certifique-se de que esta ação está atualizada
      with:
        github_token: ${{ secrets.teste1 }}
        publish_dir: ./
